export type PromptLogType =
  | 'PROMPT'
  | 'RESPONSE'
  | 'INTERROGATION_PROMPT'
  | 'INTERROGATION_RESPONSE'
  | 'FIX_PROMPT'
  | 'CLARIFICATION_PROMPT'
  | 'HELPER_AGENT_PROMPT'
  | 'HELPER_AGENT_RESPONSE'
  | 'GOAL_COMPLETION_CHECK'
  | 'GOAL_COMPLETION_RESPONSE';